### ISSUE TITLE
plugin to display a map scale

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilemill#1633]
Would be great to show a basic map scale to rough distances can be understood.

For more info see downstream issue at http://support.mapbox.com/discussions/tilemill/1254-scale

@ansis - interested in this one? I figure it could be a MM or wax extension so it could also be optionally displayed on all hosted mapbox maps?

**Comment by tmcw** [comment]
This is not a supported feature of TileMill. We'll accept Pull Requests from the community that implement this feature.
