### ISSUE TITLE
How to add text/label leader lines

### ISSUE THREAD

**Issue by maning** [mapbox/tilemill#1791]
Similar to what is shown in googlemaps (i.e. District of Columbia):
https://maps.google.com/?ll=38.754083,-83.320312&spn=69.966061,108.808594&t=m&z=4

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.

These lines are typically drawn by hand.
