### ISSUE TITLE
Upload MBTiles to MB Hosting fails with invalid version

### ISSUE THREAD

**Issue by greenwar** [mapbox/tilemill#1801]
I'm currently exporting locally to MBTiles and then uploaded to  MB Hosting. I find this is a lot faster, and I can keep old versions of exports for testing. 

This is now failing when I upload the MBTiles to MB Hosting with an error based on the version. I am incrementing the version, something like 0.5.4.4, it doesn't seem to like that. 0.5.4 works. 

The real problem, if I change the version on the export screen, it doesn't write that version to the MBTiles' metadata table. It's still pulling the version from the project settings. I can update the table in sqlite and the upload to MB works.

I would think that it should fail on export, cluing me in earlier, or work with any text/number in 'version' on upload. I do remember weird version errors on export in an earlier version of TileMill.

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.

Version numbers must be semver compliant.
