### ISSUE TITLE
Question about rendering

### ISSUE THREAD

**Issue by rickvasquez** [mapbox/tilemill#1945]
I'm currently rendering a larger job using a postGIS database pretty much rendering north america. Think rendering all roads in North America.

Specs on the system rendering are

2 x Intel E5-2640 (12 cores/24 threads @ 2.5GHZ)
64GB DDR3 1600MHZ RAM
2 X 128GB Corsair SSD in Raid 0 configuration

We have been very pleased with the performance on point data, but feel like the RAM is being underutilized as well as some of the processor.

Is there anyway to parallel rendering to the same MBTILES file? I think the system we spec'd out for rendering was outside the normal scope of what is used so we are getting gross under utilization of our bare metal resources.

Any suggestions?

**Comment by tmcw** [comment]
Closing this issue; 1 year without response.
