### ISSUE TITLE
Support font addition through GUI

### ISSUE THREAD

**Issue by stevage** [mapbox/tilemill#1974]
Currently it looks like the only way to add new fonts to TileMill is by manually adding them at the system level: downloading and copying them to /usr/share/fonts/truetype or wherever.

It would be great if there was a way to install new fonts through the web interface.

(Sorry if this has been suggested before - Github's issue searching is weak.)

**Comment by tmcw** [comment]
This is not a supported feature of TileMill. We'll accept Pull Requests from the community that implement this feature.
