### ISSUE TITLE
Older Tile Mill projects can't find data

### ISSUE THREAD

**Issue by jaeahlee** [mapbox/tilemill#2047]
Hey Dane,

When I revisit some of my older Tile Mill projects (to copy layer styles or legend styling, etc), I get a message that says my data file cannot be found. Attached a sample message below. Why is this the case?

![screen shot 2013-08-22 at 4 43 34 pm](https://f.cloud.github.com/assets/1892121/1012189/49cee72c-0b6b-11e3-8958-c4919153d04f.png)

Thanks!
Jaeah

**Comment by tmcw** [comment]
Closing this issue; 1 year without response.
