### ISSUE TITLE
Upstream needs before 0.10.2 release

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilemill#2065]
This ticket tracks upstream tags needed ideally by next week (Sept 20) for preparing a TileMill release the following week.
 
- [x] - New node-srs tag that drops the hard dependency on libgdal: https://github.com/springmeyer/node-srs/issues/30
- [x] - New Carto v0.9.5: https://github.com/mapbox/carto/issues?milestone=4&state=open - @tmcw - if you have any carto issues not assigned to that milestone that you'd like me to look at or are planning to look at yourself, please go ahead.
- [x] - New topcube tag: waiting on https://github.com/creationix/topcube/issues/22
- [x] - New `mapnik-reference` tag that declares mapnik 3.x version
- [ ] - Mapnik 3.x: https://github.com/mapnik/mapnik/milestones/Mapnik%203.x

**Comment by pnorman** [comment]
@springmeyer Is this still waiting on Mapnik 3, or is a release possible using an earlier version of Mapnik?

**Comment by springmeyer** [comment]
@pnorman - This is currently working with existing node-mapnik that bundles mapnik 3.x-dev. The last major step to getting out the next official Tilemill release is being tracked at https://github.com/mapbox/tilemill/pull/2482. Testing details for this new/upcoming build are at https://gist.github.com/bsudekum/b4606871250d9d834b3d.

So Mapnik 3.x official tag is not blocking, so I'll close this issue. That said I'm pushing really hard on Mapnik 3.x because I'd like its official tag to be what is included.
