### ISSUE TITLE
Issues adding Natural Earth raster terrain layer

### ISSUE THREAD

**Issue by palejandro** [mapbox/tilemill#2263]
Hi,

For some reason TileMill is not letting me add raster terrain data from Natural Earth. When I try to add the file (exactly as downloaded from Natural Earth) as a layer, leaving SRS as autodetect, the error message I get is that the SRS could not be determined. When I pick WGS84, it then gives me the following error message:

"Could not create datasource. No plugin found for type 'undefined' (searched in: C:\Program Files (x86)\TileMill-v0.10.1\tilemill\node_modules\mapnik\lib\mapnik\lib\mapnik\input)" 

Any idea what is going on? Was something deleted on this file extension that I should rectify?

Many thanks!

**Comment by tmcw** [comment]
Closing this issue; 1 year without response.
