### ISSUE TITLE
Assigning values

### ISSUE THREAD

**Issue by emhoa** [mapbox/tilemill#2265]
Anyone running into problems assigning values and TileMill not taking those values. I just ran into those problems today.

polygon-fill: #fff;
polygon-fill: black;

will result in a white polygon. It used to result in a black one but for some reason the overwrite is not working right now. Is this a recent bug? I tried this on two computers with TileMill and ran into the same problem. Same thing happens when I try to reassign a value for lines and texts as well. I hope this issue resolves itself tomorrow...

**Comment by tmcw** [comment]
Closing; this is not a focus of the CartoCSS precedence system.
