### ISSUE TITLE
EBUSY, stat 'C:\pagefile.sys'

### ISSUE THREAD

**Issue by oeon** [mapbox/tilemill#2281]
Error message `EBUSY, stat 'C:\pagefile.sys'` appears when trying to browse to the (root of the) C:\ drive while adding a layer.

Rebooting Windows, then starting TileMill and trying again does not cause this error upon first attempt - but it does occur with subsequent attempts to add layers. This was only occurring for me when attempting to navigation to C:\ (not D:\ or other).

Version 0.10.1 (v0.10.1-134-g31027ed) <--the dev version with FileGDB support
Windows 7

**Comment by springmeyer** [comment]
fixed by https://github.com/mapbox/tilemill/commit/2355483b3b21775bb3cb75509eb1a29ba0d7ba31
