### ISSUE TITLE
single quote bug in editor

### ISSUE THREAD

**Issue by peterm95018** [mapbox/tilemill#2324]
As noted in #2186, when using the editor, single quotes keep flipping to another character. Particularly annoying when editing IN clauses. Using 0.10.1

I'd use a browser at localhost:20009, but I'm unable to save my layer work and just get a spinner.

Is there a workaround till this is addressed? Should I pull a dev version?

**Comment by tmcw** [comment]
This is not a supported feature of TileMill. We'll accept Pull Requests from the community that implement this feature.
