### ISSUE TITLE
Map not showing using TileMill

### ISSUE THREAD

**Issue by pminhas** [mapbox/tilemill#2326]
when I open the default classes.I am getting this error.

Unable to download 'http://mapbox-geodata.s3.amazonaws.com/natural-earth-1.4.0/cultural/10m-admin-0-country-points.zip' for 'country-name' (connect ECONNREFUSED)

Please help..

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.
