### ISSUE TITLE
Error when loading POSTGIS layer: Postgis Plugin: PSQL error: ERROR:  relation "<my_table>" does not exist LINE 1: SELECT ST_SRID("geom") AS srid FROM <my_table> WHERE "geom" ...

### ISSUE THREAD

**Issue by cesaregerbino** [mapbox/tilemill#2336]
Hi all! I'm having an error when I try to load a POSTGIS layer in TileMill. The POSTGIS layer was loaded in POSTGIS using pgShapeLoader on a shapefile, and it works fine when I see it in QGIS. The complete error is

Postgis Plugin: PSQL error:
ERROR:  relation "osm_civici" does not exist
LINE 1: SELECT ST_SRID("geom") AS srid FROM osm_civici WHERE "geom" ...
                                            ^
Full sql was: 'SELECT ST_SRID("geom") AS srid FROM osm_civici WHERE "geom" IS NOT NULL LIMIT 1;'

osm_civici is the table name in my POSTGIS data base.

Any suggestion?

Thank you very much in advance!

Cesare

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.
