### ISSUE TITLE
GTFS files integration

### ISSUE THREAD

**Issue by Milanamos** [mapbox/tilemill#2340]
Hello,

I am just starting using tilemill, so maybe my question is very basic for you.
Here is my problem, I'm trying to charge a table from a GTFS file, the "stops" table, to visualize every stops on a map. In order to do that, I delete every useless column and just left on the first one the name, on the second one longitude and third one latitude. I changes every dots with commas, and save the sheet as a .csv file. But when I try to add it as a layer, it says "csv plugin : could not open " and then the link where the file is. 
Can you advice where the problem could be ?
Many thanks in advance

**Comment by tmcw** [comment]
Yep, this lies outside of TileMill: [there are tools that you can use to convert GTFS to KML and other supported file formats](http://gis.stackexchange.com/questions/49737/any-tools-to-convert-gtfs-general-transit-feed-specification-in-shp-kml).
