### ISSUE TITLE
Rendering tiles at 512px resolution

### ISSUE THREAD

**Issue by cellininicholas** [mapbox/tilemill#2350]
Is this already possible? I can't figure out how to do it.
I want to render High DPI Tiles as per the documented here:
https://developers.google.com/maps/documentation/ios/tiles#high_dpi_tiles_for_retina_devices

**Comment by mohsentaleb** [comment]
Any hopes for this issue to be resolved soon?

**Comment by springmeyer** [comment]
@mohsentaleb https://github.com/mapbox/mapbox-studio (successor to TileMill) supports retina tiles, so no this is not going to be implemented in TileMill.

**Comment by mohsentaleb** [comment]
I've set up my PostGIS local source and set up my styles. The map looks fine, but now I cant find what you said as exporting retina tiles. where can I find it?

**Comment by springmeyer** [comment]
@mohsentaleb sorry studio does not support exporting images to mbtiles at all - instead it support exporting to vector tiles stored in mbtiles. The idea is that image tiles are generated dynamically at what ever size is needed to support retina (studio internally renders 512 tiles last I looked).

**Comment by mohsentaleb** [comment]
ok, so is there any open source tools to generate raster tiles from that vector mbtiles?
I mean how do you internally export map tiles like this?
https://a.tiles.mapbox.com/v4/base.mapbox-streets+bg-e8e0d8_landuse_water_buildings_streets/5/20/12@2x.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q

**Comment by yhahn** [comment]
@mohsentaleb see https://github.com/mapbox/tilelive-vector -- this is the library that mapbox studio and the mapbox API use internally to render vector tiles as images.

**Comment by maridansoft** [comment]
Has anybody found solution to this? I want also export to 512px

**Comment by maridansoft** [comment]
Dear @springmeyer  if I would edit render.js and set all 256px to 512px, it would be enough?
