### ISSUE TITLE
Replace "900913" with "Web Mercator"

### ISSUE THREAD

**Issue by stevage** [mapbox/tilemill#2379]
The choice of SRS in the edit layer dialog is given as 900913, WGS 84, or Custom. I'm no GIS expert, but I understand that 900913 was a temporary, informal designation given to the Google Web Mercator projection before it was assigned a proper SRID, EPSG:3857.

So, I'd suggest changing the text in the dropdown to either "3857", or (more user-friendly), "Web Mercator".

Sources:

* http://gis.stackexchange.com/questions/40538/what-is-the-difference-between-epsg900913-and-epsg3857
* http://wiki.openstreetmap.org/wiki/EPSG:3857

**Comment by tmcw** [comment]
This is not a supported feature of TileMill. We'll accept Pull Requests from the community that implement this feature.
