### ISSUE TITLE
Tilemill doesn't start. Gets stuck on loading screen

### ISSUE THREAD

**Issue by jeffro-** [mapbox/tilemill#2432]
I'm on OS X Yosemite

**Comment by kjeremy** [comment]
I'm hitting this as well

**Comment by Cam** [comment]
Same for me. Seems to be still an issue.

**Comment by deckameron** [comment]
Same for me too!
I am using Yosemite 10.10.2.
As you can see on the print, the preferences item is disabled.

![captura de tela 2015-02-25 as 15 52 34](https://cloud.githubusercontent.com/assets/4404942/6377914/6ded1c02-bd06-11e4-8aee-3e77381cd8e0.png)

**Comment by dpehrson** [comment]
Just hit this too, even the developer build doesn't work.

**Comment by Vilgan** [comment]
I'm having this problem as well, also unable to open preferences. My experience is the same as @deckameron

**Comment by Cam** [comment]
I'm pretty sure Mapbox have abandoned this thing :/

**Comment by Vilgan** [comment]
@Cam Any thoughts on the best way to generate mptile files for offline use?

**Comment by Cam** [comment]
@Vilgan Not really, sorry :( But [this](http://ahoj.io/creating-mbtiles-db-for-ios-mapbox-from-hi-res-map-image) may harbour a solution. Unfortunately the iOS SDK hasn't been updated much either. It does seem to have less issues though, so could be worth a try.

**Comment by lyzidiamond** [comment]
We're still testing things out for Yosemite but you could try our latest dev release:
http://tilemill.s3.amazonaws.com/dev/TileMill-v0.10.1-312-gfaf6910.zip

We'll have one more release to get things stable for TileMill but focus has shifted over to Mapbox Studio (https://www.mapbox.com/mapbox-studio/#darwin), the next iteration of TileMill. Let me know if that works out for you and if you have questions.

**Comment by alfredotranchedone** [comment]
@lyzidiamond Dev release seems to work fine on Yosemite with Node 0.12.7

**Comment by lyzidiamond** [comment]
:+1: thanks @alfredotranchedone! Going to close here.

**Comment by garrett-eclipse** [comment]
@lyzidiamond ditto to @alfredotranchedone working for Yosemite now. Thanks
