### ISSUE TITLE
Datasource error

### ISSUE THREAD

**Issue by lordekeen** [mapbox/tilemill#2436]
Hi, im trying to use tilemill in ubuntu, i've followed the guide step by step to use open street map data, but when i load the project i get this error:

Could not create datasource for type: 'postgis' (searched for datasource plugins in '/usr/lib/mapnik/input')  encountered during parsing of layer 'landuse_gen0' in Layer at line 197

I dont have any idea of what that means.

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.
