### ISSUE TITLE
Misleading instruction in OSM Bright Tutorial? ENOENT fix

### ISSUE THREAD

**Issue by paperview** [mapbox/tilemill#2448]
After following this article: https://www.mapbox.com/tilemill/docs/guides/osm-bright-mac-quickstart/#step-2-download--import-osm-data

I see this at the end of Step 3 when I open the project in Tile Mill:

ENOENT, readdir '/Users/phil/Downloads/mapbox-osm-bright-5f237ac/shp/land-polygons-split-3857'
![osmbug1](https://cloud.githubusercontent.com/assets/2209256/5273593/f62a1afc-7a4e-11e4-8084-128adff00549.png)

The only odd thing I noticed was that after downloading osm-bright from github, I noticed that there was no shp directory, so I created my own and used wget as instructed to download the polygon files into it.

The instructions say to "Download them to the shp directory in the osm-bright folder. You can do this with wget like:"

However, you need to put the shp directory in the parent directory, not the one labelled osm-bright inside of the parent directory.

**Comment by SolomonBier** [comment]
@tommypeps sorry-what are we supposed to do? Edit the fie ?

**Comment by mikeslim7** [comment]
I resolved by
`# cd ~/Downloads/mapbox-osm-bright-*`
`# ln -s osm-bright/shp shp`
Now the error is not showing anymore

**Comment by jkokenge** [comment]
The above resolution by mikeslim7 worked for me on this error.
