### ISSUE TITLE
Interface does not adapt to HiDPi screen

### ISSUE THREAD

**Issue by anandtrex** [mapbox/tilemill#2456]
On a 2560x1440 14" display, the fonts are way too small and in general the interface is unusable. See attached screenshot.

I'm running the latest github master on a fully updated ArchLinux x64.

I must mention that the app works perfectly well when started in headless mode, and I access it using firefox. So this bug affects only the non-headless mode. (Probably related to upstream TopCube?)

![tilemill-hidpi](https://cloud.githubusercontent.com/assets/1858015/5574862/5155452c-8fcc-11e4-9cb1-30a049009c89.png)

**Comment by tmcw** [comment]
This is not a supported feature of TileMill. We'll accept Pull Requests from the community that implement this feature.
