### ISSUE TITLE
Ubuntu Utopic (14.10) packages?

### ISSUE THREAD

**Issue by Fingel** [mapbox/tilemill#2460]
Hi,
I noticed the install-tilemill.sh for ubuntu script sets up the developmentseed/mapbox PPA which doesn't appear to have been updated for the latest version of Ubnuntu. It's been out for a few months now, are there plans for it to be supported?

**Comment by springmeyer** [comment]
It is unlikely we will provide packages, since the source install now is much easier and brings down binaries of Mapnik that work across all recent and future Ubuntu versions. So give a try to installing as described in https://github.com/mapbox/tilemill#installation.

**Comment by Fingel** [comment]
Awesome! That was indeed painless. Do you reccomend keeping up to date with master? Or would a tag be more appropriate for general use. Anyway, marking this as closed (though an update on the homepage might be a good idea). Thank you!

**Comment by springmeyer** [comment]
>  Do you reccomend keeping up to date with master? Or would a tag be more appropriate for general use.

Until the next tag keeping up to date with master is just fine. Thanks for confirming the source install worked for you.
