### ISSUE TITLE
Cannot add a text-name containing a semi-colon

### ISSUE THREAD

**Issue by bedo2991** [mapbox/tilemill#2463]
How can I define within a style a 
text-name:[city:left]; where city:left is the name of the field? I've tried many possibility and none worked.
I get a "Invalid code: text-name:[city:left];"

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.
