### ISSUE TITLE
Tillemill Error

### ISSUE THREAD

**Issue by michaelpolido** [mapbox/tilemill#2487]
TileMill Suddenly Crashed.

---------------------------
TileMill Error
---------------------------
[tilemill] Error: bad allocation
[tilemill]     at C:\Program Files (x86)\TileMill-v0.10.1-291-g31027ed\tilemill\servers\Tile.bones:136:34
[tilemill]     at Function.<anonymous> (C:\Program Files (x86)\TileMill-v0.10.1-291-g31027ed\tilemill\node_modules\tilelive-mapnik\lib\mapnik_backend.js:310:25)
[tilemill]     at C:\Program Files (x86)\TileMill-v0.10.1-291-g31027ed\tilemill\node_modules\tilelive-mapnik\lib\lockingcache.js:72:26
[tilemill]     at Array.forEach (native)
[tilemill]     at LockingCache.<anonymous> (C:\Program Files (x86)\TileMill-v0.10.1-291-g31027ed\tilemill\node_modules\tilelive-mapnik\lib\lockingcache.js:71:23)
[tilemill]     at process._tickCallback (node.js:415:13)
[tilemill]     at process._tickFromSpinner (node.js:390:15)

**Comment by springmeyer** [comment]
@michaelpolido `bad allocation` means the app is running out of memory. We have an upcoming TileMill version that will be 64 bit and should solve this. Keep an eye out for it soon.

**Comment by michaelpolido** [comment]
okay thanks.
