### ISSUE TITLE
Exporting 512px tiles

### ISSUE THREAD

**Issue by barryparkin** [mapbox/tilemill#2490]
I cannot seem to export tiles at 512x512 size. Tilemill only exports to 256x256.

I'm using v0.10.1 and am trying to composite tilemill exported mbtiles files into a mapbox map in iOS along with tiles from a mapbox source. The mapbox source is 512px from v4 of their API.

I looked into editing resources/node_modules/tilelive-mapnik/lib/render.js but no luck.

A poke in the right direction would be useful.

**Comment by amaeland** [comment]
I also need to export 512x512 size tiles, currently trying to compile newest TileMill from source with mapnik v3. I also plan to change render.js setting to 512, but I also think you need to set the MetaTile size to 4?

**Comment by tmcw** [comment]
This is not a supported feature of TileMill. We'll accept Pull Requests from the community that implement this feature.
