### ISSUE TITLE
Cant open files from GeoNames.

### ISSUE THREAD

**Issue by abdelouahabb** [mapbox/tilemill#2503]
GeoNames provide CSV files (tab) but without headers, when opening them, i get this error:

`CSV Plugin: could not detect column headers with the name of wkt, geojson, x/y, or latitude/longitude - this is required for reading geometry data`

I even added the column on Excel but dident worked.
![sans titre](https://cloud.githubusercontent.com/assets/2527234/6987532/eaa7d600-da3f-11e4-9e97-914ac6ce2cfe.jpg)

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.

Likely you'll need to add headers for all the other fields and re-export as CSV.
