### ISSUE TITLE
TileMill renders background instead of blank polygon

### ISSUE THREAD

**Issue by GeoTob** [mapbox/tilemill#2523]
Using tilemill v0.10.1 and the default #countries dataset provided (or any other polygon source really), TileMill renders the background color instead of blank polygons. This issue carries on into production after exporting an mbtiles dataset.

Setting metatile size to 1 fixes this but isn't necessarily viable for large projects.

**Comment by tmcw** [comment]
This appears to be a support request: we recommend you use [GIS StackExchange](http://gis.stackexchange.com/) or [StackOverflow](http://stackoverflow.com/) for TileMill community support.

The likely issue is that the data is in your map but you haven't added style that defines how it is displayed. See the [crash course](https://www.mapbox.com/tilemill/docs/crashcourse/introduction/) for more details.
