### ISSUE TITLE
"Forbidden" message on uploading to mapbox

### ISSUE THREAD

**Issue by matkoniecz** [mapbox/tilemill#2524]
Is it part of deprecating TileMill? Should I expect that it is now impossible upload to mapbox using TilleMill?

On progress bar I see values such as

> -107169:-59:-12s remaining

> -271200:-23:-30s remaining

> 11606 days remaining

> -112660:-53:-57s remaining

> -80499:-25:-49s remaining

**Comment by willwhite** [comment]
Hi @matkoniecz. What version are you using? Is there anything relevant in the tilemill log? Can you you post it?

**Comment by matkoniecz** [comment]
At this moment I am unable to reproduce this problem. I will reopen in case of a successful replication.
