### ISSUE TITLE
tilemill export to mbtiles creates gaps at various zoom levels

### ISSUE THREAD

**Issue by jeremyeastwood** [mapbox/tilemill#2528]
Exporting a .mbtiles file from a series of geotiff raster tiles (about 5GB in total) using tilemill results in a raster layer with various tiles missing at different zoom levels (e.g. [here](https://api.mapbox.com/v4/nickponline.000000_BENCHMARK10_ortho_new/page.html?access_token=pk.eyJ1Ijoibmlja3BvbmxpbmUiLCJhIjoiRGlxNHlBbyJ9.nVTN2WNzg4aZ49eVU2zHAQ#10/53.6615/-115.1006)).  I'm seeing some errors during the export of the form:

    ERROR 4: layer.tif not recognised as a supported file format.

When I check the individual input raster tiles (e.g. layer.tif in the example above) they look ok (open ok, gdal shows they're in the correct projection).

Export command (run on linux):

    nodejs index.js export 000000_BENCHMARK10_ortho_new /mnt/dd/data/000000_BENCHMARK10/project/000000_BENCHMARK10_ortho_new/000000_BENCHMARK10_ortho_new.mbtiles CPL_DEBUG=ON --format=mbtiles --minzoom=10 --maxzoom=22 --verbose=on --concurrency=4 --bbox="-115.109022222,53.6559666667,-115.091311111,53.6667194444"

Output:

    Exporting format: mbtiles
    Loading project... done.
    Localizing project...[millstone] processing style 'style.mss'
    [millstone] processing layer 'imagelayer0'
    [millstone] processing layer 'imagelayer1'
    [millstone] processing layer 'imagelayer2'
    [millstone] processing layer 'imagelayer3'
    [millstone] processing layer 'imagelayer4'
    [millstone] processing layer 'imagelayer5'
    [millstone] processing layer 'imagelayer6'
    [millstone] processing layer 'imagelayer7'
    [millstone] processing layer 'imagelayer8'
    [millstone] processing layer 'imagelayer9'
    [millstone] processing layer 'imagelayer10'
    [millstone] processing layer 'imagelayer11'
    [millstone] processing layer 'imagelayer12'
    [millstone] processing layer 'imagelayer13'
    [millstone] processing layer 'imagelayer14'
    [millstone] processing layer 'imagelayer15'
    [millstone] processing layer 'imagelayer16'
    [millstone] processing layer 'imagelayer17'
    [millstone] processing layer 'imagelayer18'
    [millstone] processing layer 'imagelayer19'
    [millstone] processing layer 'imagelayer20'
    [millstone] processing layer 'imagelayer21'
    [millstone] processing layer 'imagelayer22'
    [millstone] processing layer 'imagelayer23'
    [millstone] processing layer 'imagelayer24'
    [millstone] processing layer 'imagelayer25'
    [millstone] processing layer 'imagelayer26'
    [millstone] processing layer 'imagelayer27'
    [millstone] processing layer 'imagelayer28'
    [millstone] processing layer 'imagelayer29'
    [millstone] processing layer 'imagelayer30'
    [millstone] processing layer 'imagelayer31'
    [millstone] processing layer 'imagelayer32'
    [millstone] processing layer 'imagelayer33'
    [millstone] processing layer 'imagelayer34'
    [millstone] processing layer 'imagelayer35'
    [millstone] processing layer 'imagelayer36'
    [millstone] processing layer 'imagelayer37'
    [millstone] processing layer 'imagelayer38'
    [millstone] processing layer 'imagelayer39'
    [millstone] processing layer 'imagelayer40'
    [millstone] processing layer 'imagelayer41'
    [millstone] processing layer 'imagelayer42'
    [millstone] processing layer 'imagelayer43'
    [millstone] processing layer 'imagelayer44'
    [millstone] processing layer 'imagelayer45'
    [millstone] processing layer 'imagelayer46'
    [millstone] processing layer 'imagelayer47'
    [millstone] processing layer 'imagelayer48'
    [millstone] processing layer 'imagelayer49'
    [millstone] processing layer 'imagelayer50'
    [millstone] processing layer 'imagelayer51'
    [millstone] processing layer 'imagelayer52'
    [millstone] processing layer 'imagelayer53'
    [millstone] processing layer 'imagelayer54'
    [millstone] processing layer 'imagelayer55'
    [millstone] processing layer 'imagelayer56'
    [millstone] processing layer 'imagelayer57'
    [millstone] processing layer 'imagelayer58'
    [millstone] processing layer 'imagelayer59'
    [millstone] processing layer 'imagelayer60'
    [millstone] processing layer 'imagelayer61'
    [millstone] processing layer 'imagelayer62'
    [millstone] processing layer 'imagelayer63'
    [millstone] processing layer 'imagelayer64'
    [millstone] processing layer 'imagelayer65'
    [millstone] processing layer 'imagelayer66'
    [millstone] processing layer 'imagelayer67'
    [millstone] processing layer 'imagelayer68'
    [millstone] processing layer 'imagelayer69'
    [millstone] processing layer 'imagelayer70'
    [millstone] processing layer 'imagelayer71'
    [millstone] processing layer 'imagelayer72'
    [millstone] processing layer 'imagelayer73'
    [millstone] processing layer 'imagelayer74'
    [millstone] processing layer 'imagelayer75'
    [millstone] processing layer 'imagelayer76'
    [millstone] processing layer 'imagelayer77'
    [millstone] processing layer 'imagelayer78'
    [millstone] processing layer 'imagelayer79'
    [millstone] processing layer 'imagelayer80'
    [millstone] processing layer 'imagelayer81'
    [millstone] processing layer 'imagelayer82'
    [millstone] processing layer 'imagelayer83'
    [millstone] processing layer 'imagelayer84'
    [millstone] processing layer 'imagelayer85'
    [millstone] processing layer 'imagelayer86'
    [millstone] processing layer 'imagelayer87'
    [millstone] processing layer 'imagelayer88'
    [millstone] processing layer 'imagelayer89'
    [millstone] processing layer 'imagelayer90'
    [millstone] finished processing '/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new'
     done.
    Rendering export
    Creating new job /mnt/dd/data/000000_BENCHMARK10/project/000000_BENCHMARK10_ortho_new/000000_BENCHMARK10_ortho_new.export
    Persisting state in /mnt/dd/data/000000_BENCHMARK10/project/000000_BENCHMARK10_ortho_new/000000_BENCHMARK10_ortho_new.export every minute
    Writing errors to /mnt/dd/data/000000_BENCHMARK10/project/000000_BENCHMARK10_ortho_new/000000_BENCHMARK10_ortho_new.export-failed
    ERROR 4: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer81.tif' not recognised as a supported file format.    

    ERROR 4: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer86.tif' not recognised as a supported file format.    

    ERROR 4: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer81.tif' not recognised as a supported file format.    

    ERROR 4: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer86.tif' not recognised as a supported file format.    

    ERROR 4: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer76.tif' not recognised as a supported file format.    

    ERROR 4: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer79.tif' not recognised as a supported file format.    

    14/2953/5286: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer86.tif' not recognised as a supported file format.    

    14/2953/5287: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer86.tif' not recognised as a supported file format.    

    14/2954/5286: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer86.tif' not recognised as a supported file format.    

    14/2954/5287: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer86.tif' not recognised as a supported file format.    

    12/738/1321: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer81.tif' not recognised as a supported file format.    

    13/1476/2643: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer76.tif' not recognised as a supported file format.    

    13/1477/2643: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer76.tif' not recognised as a supported file format.    

    16/11814/21146: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer79.tif' not recognised as a supported file format.    

    16/11814/21147: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer79.tif' not recognised as a supported file format.    

    16/11815/21146: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer79.tif' not recognised as a supported file format.    

    16/11815/21147: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer79.tif' not recognised as a supported file format.    

    15/5906/10572: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer81.tif' not recognised as a supported file format.    

    15/5906/10573: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer81.tif' not recognised as a supported file format.    

    15/5907/10572: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer81.tif' not recognised as a supported file format.    

    15/5907/10573: `/home/ubuntu/Documents/MapBox/project/000000_BENCHMARK10_ortho_new/layers/imagelayer81.tif' not recognised as a supported file format.    

    [21m 18s] Part(1/1) 100.0000% 59.4k/59.4k @ 123/s | 0s left | ✓ 28.0k ■ 0 □ 31.4k fail 15
    finished

**Comment by jeremyeastwood** [comment]
@springmeyer any ideas?

**Comment by springmeyer** [comment]
How are you loading your tiffs into the project? Using a VRT perhaps?

**Comment by jeremyeastwood** [comment]
I'm building up the project.mml and referencing all the geotiffs directly there.

project.mml:
https://gist.github.com/jeremyeastwood/d3f1fae5ec02a382a410

style.mss:
https://gist.github.com/jeremyeastwood/3d67948d94ac128c8a12

**Comment by springmeyer** [comment]
Okay. Ask about VRT's just in case https://github.com/mapnik/node-mapnik/issues/437 might be involved. But I don't think it is. However I also don't know what is wrong. One idea is that your system might be running out of file handles or something like that. Can you use VRT's or otherwise merge some of the files together? Something to consider.

**Comment by jeremyeastwood** [comment]
merging to vrt before export seems to be working better - may well have been a system limitation as you suggested (the missing tiles occur more often on larger projects).

Thanks for the advice - much appreciated.

**Comment by springmeyer** [comment]
Great news so far @jeremyeastwood. I'll close this then, please re-open if you hit more trouble.
