### ISSUE TITLE
A way to export .mss from Mapbox and import to TileMill?

### ISSUE THREAD

**Issue by jerald-acacus** [mapbox/tilemill#2531]
Is there anyway that I can export a .mss of a project in Mapbox Studio to TileMill? Or just any .mss I can download/resource that will show a map with satellite-like view.

**Comment by tmcw** [comment]
Mapbox Studio styles point to remote, vector tile datasources, while TileMill styles point to local, file or database resources. The two aren't compatible.

To generate a satellite map, you'll need to gather and process satellite data, like Blue Marble, and render the map - or use an online service with a satellite map. Unlike road maps, satellite maps don't have much in the way of TileMill or Mapbox Studio-level styles to create - they're mostly a product of data processing.

**Comment by jerald-acacus** [comment]
So there is no way to get these remote vector tile sources that Mapbox uses manually? I just found out that I can copy .mss styles from Mapbox to TileMill and it works. But I couldn't find a way to extract a layer from a Mapbox style and put it in TileMill.
