### ISSUE TITLE
On chrome, web interface redirects to http://localhost:20009/#restart on project creation or layer save

### ISSUE THREAD

**Issue by YenTheFirst** [mapbox/tilemill#2534]
Evironment: Ubuntu 14.04, current HEAD of tilemill, google chrome 45.0.2454.101

Steps to reproduce:
1. Start a tilemill server
2. On google chrome, go to localhost:20009
3. Create a project.
4. You are then redirected to http://localhost:20009/#restart, which contains only the text "Error: Page not Found".

Alternatively:
1. Start a tilemill server
2. On google chrome, go to localhost:20009
3. Open any project
4. Open a layer for editing, then save the layer. (no modification necessary)
5. You are then redirected to http://localhost:20009/#restart, which contains only the text "Error: Page not Found".

This bug does not occur on Firefox. This bug started occurring a few weeks ago, without any update or configuration change in tilemill, so I expect it's related to a recent chrome auto-update.

**Comment by YenTheFirst** [comment]
After further investigation by a coworker, it seems that the cause is the following:

on project creation (https://github.com/mapbox/tilemill/blob/master/views/ProjectAdd.bones#L31) or layer save (https://github.com/mapbox/tilemill/blob/master/views/Layer.bones#L376), all elements with class 'close' are clicked.

This includes two spans in the Pane template (particularly, https://github.com/mapbox/tilemill/blob/master/templates/Pane._#L5). I guess the click event from these spans is bubbling up to the anchor, and then being treated as a direct click on that button.

As a workaround, changing `this.$('.close').click();` to `this.$('a[href="#close"]').click();` works, which matches what views/App.bones currently does. However, I'm not sure if this is the correct fix. `this.$('a.close').click();` also should work.

Actually, looking for similar code, it seems the 'save' button on new creating new stylesheet also exhibits this behavior.

**Comment by stevage** [comment]
Thanks for investigating - I ran into the same problem, with a much older version of TileMill. Knowing that this doesn't happen in Firefox is pretty useful!

**Comment by Nor67** [comment]
I'm having the exact same problem with my local TileMill installation. Version 0.10.1 (v0.10.1-291-g31027ed) running on OSX 10.12.5. 
Adding new stylesheet results in Error: Page not found and the new stylesheet is not added. Creating a new project also results in the same error but the new project actually is added.  I've checked all 3 files that florianf fixed and the fixes are all there. 
Any idea how to solve this? Thanks.

**Comment by Makosak** [comment]
Also running into this issue, even if running on a web browser other than Chrome. It's not clear what the solution is -- was there a different build recommended? Do I have to compile from scratch instead of using the zip download? I'm only using the application, not developing on this project; any help for my class would be super! (from the instructor's perspective -- if it's a workable and straightforward solution I could have the class follow as well)

**Comment by csytsma** [comment]
I'm not familiar with the cause of the issue, but you can manually add a new Stylesheet by adding the .mss file in the "../MapBox/project/<project name>/" folder, then try loading the project.
