### ISSUE TITLE
Application doesn't start …

### ISSUE THREAD

**Issue by elatezet** [mapbox/tilemill#2542]
Unfortunately the app does not start.

![bildschirmfoto 2016-01-20 um 09 06 07](https://cloud.githubusercontent.com/assets/8506216/12443022/0d110946-bf55-11e5-9394-4428b67adc45.png)

I attached the crash report.

[node_2016-01-20-085844_graphit.crash.zip](https://github.com/mapbox/tilemill/files/97107/node_2016-01-20-085844_graphit.crash.zip)

**Comment by tmcw** [comment]
Same as #2439
