### ISSUE TITLE
End of life/deprecated notice in readme

### ISSUE THREAD

**Issue by bsudekum** [mapbox/tilemill#2543]
This project is no longer maintained and new, better products have since been released. For people who do stumble upon this repo we should:

* let them know this project is no longer maintained
* point them to Mapbox Studio

/cc @lyzidiamond @springmeyer

**Comment by tmcw** [comment]
Just to be clear: **Mapbox employees no longer work on TileMill in their work time**. This does _not_ mean that TileMill is unavailable, or we don't accept PRs. We're happy to extend commit rights to interested contributors and want to encourage a long open source life to TileMill.
