### ISSUE TITLE
Endless spinning on El Capitan (Mac OS X 10.11.3,  Tilemill v0.10.1)

### ISSUE THREAD

**Issue by gabssnake** [mapbox/tilemill#2550]
TileMill 0.10.1 does not go past the spinner at startup on El Capitan (Mac OS X 10.11.3).

Related to : https://github.com/mapbox/tilemill/issues/2356
And : https://github.com/mapbox/tilemill/issues/2380

**Comment by johndpope** [comment]
bump

**Comment by jerald-acacus** [comment]
This can be resolved by downloading TileMill-0.10.0 from http://tilemill.s3.amazonaws.com/index.html?path=archive/. Then install it and when it gets to the endless spinning part go to Update Preferences (Under Check for Updates) in the menu. Then turn on Install Developer Builds and do an update.

**Comment by gabssnake** [comment]
Big thanks @jerald-acacus, that worked for me

**Comment by aywh1991** [comment]
yes it works for me too, thanks a lot

**Comment by JeongJun-Lee** [comment]
It works for Sierra
