### ISSUE TITLE
TileMill not starting on my Mac

### ISSUE THREAD

**Issue by schorschie** [mapbox/tilemill#2564]
Hello, 
I just downloaded tile mill and it is not starting properly. It stay's in a endless wait cursor.
I've attached the crash log. 
Are there maybe any quickfixes available?
[node_2016-07-14-182800_Mac-mini.crash.zip](https://github.com/mapbox/tilemill/files/364330/node_2016-07-14-182800_Mac-mini.crash.zip)

**Comment by DoomyTheFroomy** [comment]
@schorschie please see https://github.com/mapbox/tilemill/issues/2539

**Comment by tmcw** [comment]
Closing in favor of #2539

**Comment by cre80vty** [comment]
@DoomyTheFroomy your link seems broken.
Here's the correct one https://github.com/tilemill-project/tilemill/issues/2539
