### ISSUE TITLE
lat long tooltip

### ISSUE THREAD

**Issue by ian29** [mapbox/tilemill#878]
google maps labs has a great feature that displays lat long as a tooltip when you hold down shift. this would be massively helpful when crosschecking for geocoding errors, locating features, etc. 

![tooltip](https://img.skitch.com/20111104-j11rg1rtgj1wkrh23k47n695jt.png)

**Comment by tmcw** [comment]
Closing as idle. PRs are accepted that would completed this task but it is not one of my own priorities to implement it myself.
